### Create New User | signup

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "aungzawphyo@gmail.com",
    "password": "password"
}

### Sign In

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "linnkhit@gmail.com",
    "password": "password"
}

### Who am I

GET  http://localhost:3000/auth/whoami
Content-Type: application/json


### Singout

POST  http://localhost:3000/auth/signout
Content-Type: application/json

### Find Particular Single User

GET  http://localhost:3000/auth/2
Content-Type: application/json


### Find Users

GET  http://localhost:3000/auth?email=aungaung@gmail.com
Content-Type: application/json



### Remove User

DELETE   http://localhost:3000/auth/54
Content-Type: application/json


### Update User

PATCH  http://localhost:3000/auth/2
Content-Type: application/json

{
}